### ISSUE TITLE
Cannot read property 'send' of undefined

### ISSUE THREAD

**Issue by DaniloL88** [eartharoid/DiscordTickets#11]
[04:55:26 | INIT] Initialising logger (v1.1.9)
[04:55:26 | INIT] Creating new log file ("./logs/17-05-2020-04-55-26.log")
[04:55:26 | INIT] Initialised logger with the following custom types:
[04:55:26 | INFO] Starting up...
[04:55:27 | INFO] Initialising bot...
[04:55:27 | INFO] > Loading '!add' command
[04:55:27 | INFO] > Loading '!close' command
[04:55:27 | INFO] > Loading '!help' command
[04:55:27 | INFO] > Loading '!new' command
[04:55:27 | INFO] > Loading '!ping' command
[04:55:27 | INFO] > Loading '!remove' command
[04:55:27 | INFO] Connected to Discord API
[04:55:27 | INFO] Logged in as (Name of the bot)
/home/ticketbot/index.js:105
    client.channels.get(config.logChannel).send(embed)
                                          ^

TypeError: Cannot read property 'send' of undefined
    at Client.client.once (/home/ticketbot/index.js:105:43)
    at Object.onceWrapper (events.js:286:20)
    at Client.emit (events.js:203:15)
    at WebSocketConnection.triggerReady (/home/ticketbot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:128:17)
    at WebSocketConnection.checkIfReady (/home/ticketbot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:144:61)
    at ReadyHandler.handle (/home/ticketbot/node_modules/discord.js/src/client/websocket/packets/handlers/Ready.js:80:8)
    at WebSocketPacketManager.handle (/home/ticketbot/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:108:65)
    at WebSocketConnection.onPacket (/home/ticketbot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:336:35)
    at WebSocketConnection.onMessage (/home/ticketbot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:299:17)
    at WebSocket.onMessage (/home/ticketbot/node_modules/ws/lib/event-target.js:120:16)

**Comment by eartharoid** [comment]
Have you set the id of `logChannel` in your config? Make sure the channel exists if you have.

**Comment by DaniloL88** [comment]
Yes, I have

**Comment by eartharoid** [comment]
The bot needs read & send messages permissions in that channel.

**Comment by DaniloL88** [comment]
Yes I know, but if he hasn't entered, how can I give it to him? Do I put it directly from the bot creation on Discord?

**Comment by eartharoid** [comment]
Have you not invited the bot to the server?
Invite the bot with this link: https://discord.com/oauth2/authorize?client_id=ID-OF-YOUR-BOT&permissions=27664&scope=bot but change `ID-OF-YOUR-BOT` to the id from https://discord.com/developers/applications/

**Comment by DaniloL88** [comment]
The bot wasn't in the Discord Server, it was my bad. But now I've another error (It has all permissions):

TypeError: Cannot read property 'member' of undefined
    at Client.client.once (/home/ticketbot/index.js:109:40)
    at Object.onceWrapper (events.js:286:20)
    at Client.emit (events.js:203:15)
    at WebSocketConnection.triggerReady (/home/ticketbot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:128:17)
    at WebSocketConnection.checkIfReady (/home/ticketbot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:144:61)
    at GuildCreateHandler.handle (/home/ticketbot/node_modules/discord.js/src/client/websocket/packets/handlers/GuildCreate.js:13:31)
    at WebSocketPacketManager.handle (/home/ticketbot/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:108:65)
    at WebSocketConnection.onPacket (/home/ticketbot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:336:35)
    at WebSocketConnection.onMessage (/home/ticketbot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:299:17)
    at WebSocket.onMessage (/home/ticketbot/node_modules/ws/lib/event-target.js:120:16)

**Comment by eartharoid** [comment]
Make sure you have discord.js v11 not v12: `npm i discord.js@11.6.4`

**Comment by DaniloL88** [comment]
Same problem

**Comment by DaniloL88** [comment]
Another question: can we talk in Discord? Danilo#1062

**Comment by eartharoid** [comment]
*You don't exist*
![image](https://user-images.githubusercontent.com/20905071/82158487-21e34600-9880-11ea-8c2a-0d5803b056b8.png)

Join my support server: https://discord.gg/pXc9vyC
