### ISSUE TITLE
I have this error:

### ISSUE THREAD

**Issue by ImKill6r** [eartharoid/DiscordTickets#110]
[12:05:20 | ERROR] TypeError: Cannot read property 'member' of undefined
    at Object.execute (C:\Users\Jesus\Desktop\᲻\Bots\DiscordTickets reaction\src\events\ready.js:37:44)
    at Client.<anonymous> (C:\Users\Jesus\Desktop\᲻\Bots\DiscordTickets reaction\src\index.js:130:68)
    at Client.emit (events.js:315:20)
    at WebSocketManager.triggerClientReady (C:\Users\Jesus\Desktop\᲻\Bots\DiscordTickets reaction\node_modules\discord.js\src\client\websocket\WebSocketManager.js:431:17)
    at WebSocketManager.checkShardsReady (C:\Users\Jesus\Desktop\᲻\Bots\DiscordTickets reaction\node_modules\discord.js\src\client\websocket\WebSocketManager.js:415:10)
    at WebSocketShard.<anonymous> (C:\Users\Jesus\Desktop\᲻\Bots\DiscordTickets reaction\node_modules\discord.js\src\client\websocket\WebSocketManager.js:197:14)
    at WebSocketShard.emit (events.js:315:20)
    at WebSocketShard.checkReady (C:\Users\Jesus\Desktop\᲻\Bots\DiscordTickets reaction\node_modules\discord.js\src\client\websocket\WebSocketShard.js:475:12)
    at WebSocketShard.onPacket (C:\Users\Jesus\Desktop\᲻\Bots\DiscordTickets reaction\node_modules\discord.js\src\client\websocket\WebSocketShard.js:447:16)
    at WebSocketShard.onMessage (C:\Users\Jesus\Desktop\᲻\Bots\DiscordTickets reaction\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
[12:05:53 | WARN] An error was not caught
[12:05:53 | WARN] Uncaught TypeError: Cannot read property 'id' of undefined
[12:05:53 | ERROR] TypeError: Cannot read property 'id' of undefined
    at Object.execute (C:\Users\Jesus\Desktop\᲻\Bots\DiscordTickets reaction\src\events\message.js:59:34)

**Comment by eartharoid** [comment]
You need to configure the required values in the config file: https://github.com/eartharoid/DiscordTickets/wiki/Configuration#notice
