### ISSUE TITLE
Uncaught TypeError: Cannot read property 'member' of undefined node

### ISSUE THREAD

**Issue by steth60** [eartharoid/DiscordTickets#116]
After install and first running the bot, I'm receiving the following error.

`[11:23:48 | WARN] An error was not caught
[11:23:48 | WARN] Uncaught TypeError: Cannot read property 'member' of undefined
[11:23:48 | ERROR] TypeError: Cannot read property 'member' of undefined
    at Object.execute (/root/DiscordTickets/src/events/ready.js:37:44)
    at Client.<anonymous> (/root/DiscordTickets/src/index.js:132:68)
    at Client.emit (events.js:315:20)
    at WebSocketManager.triggerClientReady (/root/DiscordTickets/node_modules/discord.js/src/client/websocket/WebSocketManager.js:431:17)
    at WebSocketManager.checkShardsReady (/root/DiscordTickets/node_modules/discord.js/src/client/websocket/WebSocketManager.js:415:10)
    at WebSocketShard.<anonymous> (/root/DiscordTickets/node_modules/discord.js/src/client/websocket/WebSocketManager.js:197:14)
    at WebSocketShard.emit (events.js:315:20)
    at WebSocketShard.checkReady (/root/DiscordTickets/node_modules/discord.js/src/client/websocket/WebSocketShard.js:475:12)
    at Object.module.exports [as READY] (/root/DiscordTickets/node_modules/discord.js/src/client/websocket/handlers/READY.js:20:9)
    at WebSocketManager.handlePacket (/root/DiscordTickets/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)

`

**Comment by eartharoid** [comment]
You need to set the required config values, including the `guild` ID: https://github.com/eartharoid/DiscordTickets/wiki/Configuration#notice

**Comment by steth60** [comment]
These vaules have been defined, as shown below
`	guild: '803970124271845377', // ID of your guild (REQUIRED)
	staff_role: '807927067558805525', // ID of your Support Team role (REQUIRED)

	tickets: {
		category: '814102616761303070', // ID of your tickets category (REQUIRED)`

**Comment by eartharoid** [comment]
Have you added the bot to your server? `https://discord.com/api/oauth2/authorize?client_id=YOUR_BOT_ID_HERE&permissions=8&scope=bot`

**Comment by steth60** [comment]
This was the problem, Thank you so much.
