### ISSUE TITLE
TypeError: Discord.RichEmbed is not a constructor

### ISSUE THREAD

**Issue by calebdatechguy** [eartharoid/DiscordTickets#12]
I have done the full setup and whenever i launch, here is what the cmd looks like:

##     ##  ##       ##  ##   ##          ##    ##
   ##     ##  ##       #####    ######      ##     ######
   ##     ##  ##       ##  ##   ##          ##          ##
   ##     ##  ##    ## ##   ##  ##          ##    ##    ##
   ##    ####  ######  ##    ## ########    ##     ######

DiscordTickets v1.0.0 - Made By Eartharoid
https://github.com/eartharoid/DiscordTickets

==========================================================================

[00:48:43 | INIT] Initialising logger (v1.1.9)
[00:48:43 | INIT] Creating new log file ("./logs/06-06-2020-00-48-43.log")
[00:48:43 | INIT] Initialised logger with the following custom types:
[00:48:43 | INFO] Starting up...
[00:48:43 | INFO] Initialising bot...
[00:48:43 | INFO] > Loading '?add' command
[00:48:43 | INFO] > Loading '?close' command
[00:48:43 | INFO] > Loading '?help' command
[00:48:43 | INFO] > Loading '?new' command
[00:48:43 | INFO] > Loading '?ping' command
[00:48:43 | INFO] > Loading '?remove' command
[00:48:43 | INFO] Connected to Discord API
[00:48:43 | INFO] Logged in as Xzobe Tickets#6907
[00:48:43 | WARN] An error was not caught
[00:48:43 | ERROR] Uncaught error:
TypeError: Discord.RichEmbed is not a constructor
    at Client.<anonymous> (C:\Users\Caleb\Desktop\Discord Bots\Discord Tickets\index.js:100:19)
    at Object.onceWrapper (events.js:421:28)
    at Client.emit (events.js:315:20)
    at WebSocketManager.triggerClientReady (C:\Users\Caleb\Desktop\Discord Bots\Discord Tickets\node_modules\discord.js\src\client\websocket\WebSocketManager.js:433:17)
    at WebSocketManager.checkShardsReady (C:\Users\Caleb\Desktop\Discord Bots\Discord Tickets\node_modules\discord.js\src\client\websocket\WebSocketManager.js:417:10)
    at WebSocketShard.<anonymous> (C:\Users\Caleb\Desktop\Discord Bots\Discord Tickets\node_modules\discord.js\src\client\websocket\WebSocketManager.js:199:14)
    at WebSocketShard.emit (events.js:315:20)
    at WebSocketShard.checkReady (C:\Users\Caleb\Desktop\Discord Bots\Discord Tickets\node_modules\discord.js\src\client\websocket\WebSocketShard.js:467:12)
    at Object.module.exports [as READY] (C:\Users\Caleb\Desktop\Discord Bots\Discord Tickets\node_modules\discord.js\src\client\websocket\handlers\READY.js:20:9)
    at WebSocketManager.handlePacket (C:\Users\Caleb\Desktop\Discord Bots\Discord Tickets\node_modules\discord.js\src\client\websocket\WebSocketManager.js:386:31)

I am not sure how to fix it. I have done research but can't figure it out.

**Comment by eartharoid** [comment]
I'm guessing it's a discord.js v12 thing.
Type "npm i discord.js@11.6.4" in your terminal (in the same folder).
Don't forget you need to edit the config and add your new bot to your
server.

**Comment by timmy0909** [comment]
You have to put this: 
`const exampleEmbed1 = new Discord.MessageEmbed()`

If you wanna make new Embeds you have to put exampleEmbed2.

**Comment by eartharoid** [comment]
It has worked fine in testing last year with naming most of the embed variables the same.

**Comment by calebdatechguy** [comment]
Ok thanks
