### ISSUE TITLE
bug new ticket 

### ISSUE THREAD

**Issue by GalackQSM** [eartharoid/DiscordTickets#26]
[23:11:43 | INFO] Backup#5417 used the 'new' command
[23:11:44 | ERROR] DiscordAPIError: Invalid Form Body
parent_id: Value "" is not snowflake.
    at RequestHandler.execute (C:\Users\cynthia\Desktop\DiscordTickets-master\node_modules\discord.js\src\rest\RequestHandler.js:170:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by eartharoid** [comment]
Have you set all of the required values in the config? ID of guild, ticket category, and support role?

**Comment by GalackQSM** [comment]
yes, suddenly we can put it on several servers the bot?

**Comment by eartharoid** [comment]
huh?
You can currently only use the bot on 1 server.

**Comment by GalackQSM** [comment]
ah okay ^^
