### ISSUE TITLE
trouble using discord bot

### ISSUE THREAD

**Issue by artificialpaper** [eartharoid/DiscordTickets#36]

**Comment by eartharoid** [comment]
A template? 🤔

**Comment by artificialpaper** [comment]
uh

**Comment by artificialpaper** [comment]
so i got it to work but now i get the error [17:32:38 | ERROR] TypeError: Cannot read property 'member' of undefined

**Comment by eartharoid** [comment]
Does it say what line the error came from below?

**Comment by artificialpaper** [comment]
at Object.execute (/home/container/src/events/ready.js:36:44)
    at Client.<anonymous> (/home/container/src/index.js:98:68)
    at Client.emit (events.js:314:20)
    at WebSocketManager.triggerClientReady (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:431:17)
    at WebSocketManager.checkShardsReady (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:415:10)
    at WebSocketShard.<anonymous> (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:197:14)
    at WebSocketShard.emit (events.js:314:20)
    at WebSocketShard.checkReady (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:475:12)
    at WebSocketShard.onPacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:447:16)
    at WebSocketShard.onMessage (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)

**Comment by artificialpaper** [comment]
do i need to use a specific version of node

**Comment by artificialpaper** [comment]
im currently using v14

**Comment by eartharoid** [comment]
v14 is fine.
As shown in the instructions on the wiki, you need to configure 3 or 4 Discord IDs in your config. You havem't set `guild` (or it is incorrect).

**Comment by artificialpaper** [comment]
after following the wiki instructions, i still get

[18:11:44 | WARN] Uncaught TypeError: Cannot read property 'tag_name' of undefined
[18:11:44 | ERROR] TypeError: Cannot read property 'tag_name' of undefined
    at /home/container/src/modules/updater.js:28:27
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[18:11:45 | INFO] Authenticated as DreamZone#8735
[18:11:45 | WARN] An error was not caught
[18:11:45 | WARN] Uncaught TypeError: Cannot read property 'member' of undefined
[18:11:45 | ERROR] TypeError: Cannot read property 'member' of undefined
    at Object.execute (/home/container/src/events/ready.js:36:44)
    at Client.<anonymous> (/home/container/src/index.js:98:68)
    at Client.emit (events.js:314:20)
    at WebSocketManager.triggerClientReady (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:431:17)
    at WebSocketManager.checkShardsReady (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:415:10)
    at WebSocketShard.<anonymous> (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:197:14)
    at WebSocketShard.emit (events.js:314:20)
    at WebSocketShard.checkReady (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:475:12)
    at WebSocketShard.onPacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:447:16)
    at WebSocketShard.onMessage (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)

**Comment by eartharoid** [comment]
Have you fully configured the bot and restarted the bot after doing so? The guild is still missing.

**Comment by eartharoid** [comment]
@artificialpaper still need help?

**Comment by artificialpaper** [comment]
uh i give up at this point

**Comment by eartharoid** [comment]
oof
