### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by WoollenPanda275** [eartharoid/DiscordTickets#44]
Ive added the bot to my server and when I do "(prefix)new" it says that the ticket was created but no new channels are opened/created. I follow the step by step set-up wiki and not really sure where to go from here

**Comment by eartharoid** [comment]
Is there an error in the terminal? I'm guessing you haven't given the bot permissions.

**Comment by WoollenPanda275** [comment]
This is the terminal



[17:02:40 | INFO] Loaded 9 events and 12 commands
[17:02:41 | INFO] Authenticated as CATALYST UTILITIES#9032
[17:02:41 | INFO] 'ADMINISTRATOR' permission has been granted
[17:05:22 | INFO] ajay.ra0#6256 used the 'new' command
[17:05:23 | ERROR] DiscordAPIError: Invalid Form Body
parent_id: Value "" is not snowflake.
    at RequestHandler.execute (C:\Users\Ajayk\OneDrive\Desktop\Discord Bots\DiscordTickets-master\node_modules\discord.js\src\rest\RequestHandler.js:170:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[17:06:08 | INFO] ajay.ra0#6256 used the 'help' command
[17:06:44 | INFO] ajay.ra0#6256 used the 'new' command
[17:06:45 | ERROR] DiscordAPIError: Invalid Form Body
parent_id: Value "" is not snowflake.
    at RequestHandler.execute (C:\Users\Ajayk\OneDrive\Desktop\Discord Bots\DiscordTickets-master\node_modules\discord.js\src\rest\RequestHandler.js:170:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[17:07:17 | INFO] ajay.ra0#6256 used the 'tickets' command
[17:07:32 | INFO] Received a DM from ajay.ra0#6256: &7new
[17:08:21 | INFO] ajay.ra0#6256 used the 'new' command
[17:08:21 | ERROR] DiscordAPIError: Invalid Form Body
parent_id: Value "" is not snowflake.
    at RequestHandler.execute (C:\Users\Ajayk\OneDrive\Desktop\Discord Bots\DiscordTickets-master\node_modules\discord.js\src\rest\RequestHandler.js:170:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[17:09:03 | INFO] Received a DM from ajay.ra0#6256: &7help
[17:10:21 | INFO] Received a DM from ajay.ra0#6256: &7help
[17:10:42 | INFO] ajay.ra0#6256 used the 'new' command
[17:11:54 | INFO] ajay.ra0#6256 used the 'help' command
[17:12:20 | INFO] ajay.ra0#6256 used the 'tickets' command
[17:12:35 | INFO] Received a DM from ajay.ra0#6256: &close
[17:12:43 | INFO] Received a DM from ajay.ra0#6256: &7close
[17:12:52 | INFO] ajay.ra0#6256 used the 'close' command
[17:18:53 | INFO] ajay.ra0#6256 used the 'new' command
[17:19:25 | INFO] ajay.ra0#6256 used the 'new' command
[17:19:46 | INFO] ajay.ra0#6256 used the 'close' command
[17:20:04 | INFO] ajay.ra0#6256 used the 'help' command
[17:21:07 | INFO] ajay.ra0#6256 used the 'close' command

**Comment by eartharoid** [comment]
In `user/config.js` you need to set the values of `guild`, `support_role`, and `tickets.category` to Discord IDs ("snowflakes").

**Comment by WoollenPanda275** [comment]
ah okay i must have missed the category. Ive done the othrs

**Comment by WoollenPanda275** [comment]
what do i do about the other tickets as I cant see them so cannot cloe them?

**Comment by eartharoid** [comment]
Delete your database (`user/storage.db` for the default, SQLite) and restart the bot to regenerate it.

**Comment by WoollenPanda275** [comment]
Okay. thankyou for the help
