### ISSUE TITLE
Errors on commands: TypeError: fields.flat is not a function

### ISSUE THREAD

**Issue by DAHPr0gram3r** [eartharoid/DiscordTickets#46]
Bot starts fine but when ever i run a command it errors out console log follows:
`[03:10:02 | INFO] Authenticated as Novus Networks Dev#6711
[03:10:02 | INFO] 'ADMINISTRATOR' permission has been granted
[03:10:24 | INFO] dahpr0gam3r#2405 used the 'new' command
[03:10:24 | ERROR] TypeError: fields.flat is not a function
    at Function.normalizeFields (/home/ubuntu/bots/DiscordTickets-master/node_modules/discord.js/src/structures/MessageEmbed.js:450:8)
    at MessageEmbed.setup (/home/ubuntu/bots/DiscordTickets-master/node_modules/discord.js/src/structures/MessageEmbed.js:78:91)
    at new MessageEmbed (/home/ubuntu/bots/DiscordTickets-master/node_modules/discord.js/src/structures/MessageEmbed.js:18:10)
    at embedLikes.map.e (/home/ubuntu/bots/DiscordTickets-master/node_modules/discord.js/src/structures/APIMessage.js:166:40)
    at Array.map (<anonymous>)
    at APIMessage.resolveData (/home/ubuntu/bots/DiscordTickets-master/node_modules/discord.js/src/structures/APIMessage.js:166:31)
    at TextChannel.send (/home/ubuntu/bots/DiscordTickets-master/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:166:62)
    at guild.channels.create.then (/home/ubuntu/bots/DiscordTickets-master/src/commands/new.js:121:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)
`

**Comment by eartharoid** [comment]
Update Node.JS to at least v12.
