### ISSUE TITLE
Member Error

### ISSUE THREAD

**Issue by Linspecteur** [eartharoid/DiscordTickets#51]
[10:31:34 | ERROR] TypeError: Cannot read property 'member' of undefined
    at Object.execute (C:\Serveur\Bot\DiscordTickets-master\src\events\ready.js:37:44)
    at Client.<anonymous> (C:\Serveur\Bot\DiscordTickets-master\src\index.js:130:68)
    at Client.emit (events.js:315:20)
    at WebSocketManager.triggerClientReady (C:\Serveur\Bot\DiscordTickets-master\node_modules\discord.js\src\client\websocket\WebSocketManager.js:431:17)
    at WebSocketManager.checkShardsReady (C:\Serveur\Bot\DiscordTickets-master\node_modules\discord.js\src\client\websocket\WebSocketManager.js:415:10)
    at WebSocketShard.<anonymous> (C:\Serveur\Bot\DiscordTickets-master\node_modules\discord.js\src\client\websocket\WebSocketManager.js:197:14)
    at WebSocketShard.emit (events.js:315:20)
    at WebSocketShard.checkReady (C:\Serveur\Bot\DiscordTickets-master\node_modules\discord.js\src\client\websocket\WebSocketShard.js:475:12)
    at WebSocketShard.onPacket (C:\Serveur\Bot\DiscordTickets-master\node_modules\discord.js\src\client\websocket\WebSocketShard.js:447:16)
    at WebSocketShard.onMessage (C:\Serveur\Bot\DiscordTickets-master\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)

**Comment by eartharoid** [comment]
Either:
- You haven't set `guild` in `user/config.js`
- Or, you didn't add your bot to your server

If you haven't set the `guild` ID, you are probably also missing `support_role` and `tickets.category` IDs as well. All three are required.

**Comment by Linspecteur** [comment]
![image](https://user-images.githubusercontent.com/48238287/96166874-ddd39a80-0f1e-11eb-86ad-7a5a2f6fc875.png)

It's Ok thanks !

**Comment by eartharoid** [comment]
*Ew why are you using Internet Explorer 🤮*

By the way, you can change the config to this if you just want the bot to be "**Playing** Norway Support" all the time.
```js
presences: [
  {
    activity: 'Norway Sypport',
    type: 'PLAYING'
  },
],
append_presence: ' ',
```

**Comment by Linspecteur** [comment]
No it's just on my virtual server lol
