### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by WoollenPanda275** [eartharoid/DiscordTickets#52]
First off, sorry for all the issues I've reported in the last few days.
Its been working fine when I've been hosting it locally but now I'm trying it online it wants none of it

Ive recently decided to start hosting the bot online and It keeps giving me this error I've asked multiple people and they've had no idea on how to help. 

npm WARN @eartharoid/discordtickets@2.0.1 requires a peer of mysql2@2.x but none is installed. You must install peer dependencies yourself.
npm WARN @eartharoid/discordtickets@2.0.1 requires a peer of mariadb@2.x but none is installed. You must install peer dependencies yourself.
npm WARN @eartharoid/discordtickets@2.0.1 requires a peer of pg@8.x but none is installed. You must install peer dependencies yourself.
npm WARN @eartharoid/discordtickets@2.0.1 requires a peer of tedious@9.x but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 355 packages in 13.958s

23 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

This what happens when I start running it.

[18:13:18 | INFO] Using SQLite storage
/home/container/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:81
        throw new Error(`Please install ${moduleName} package manually`);
        ^

Error: Please install sqlite3 package manually
    at ConnectionManager._loadDialectModule (/home/container/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:81:15)
    at new ConnectionManager (/home/container/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:24:21)
    at new SqliteDialect (/home/container/node_modules/sequelize/lib/dialects/sqlite/index.js:15:30)
    at new Sequelize (/home/container/node_modules/sequelize/lib/sequelize.js:340:20)
    at Object.<anonymous> (/home/container/src/index.js:83:14)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
container@pterodactyl~ Server marked as offline...

**Comment by eartharoid** [comment]
`sqlite3` should have been installed when if you did `npm i` but it may have failed because I think you need build tools. If you can't install SQLite, install `mysql2` and connect to a MySQL database instead - I'm assuming your Pterodactyl host gives you a database. You'll need to edit the `DB_` options in `user/.env` and set `storage.type` to `'mysql'` in `user/config.js`.
