### ISSUE TITLE
Help please :)

### ISSUE THREAD

**Issue by Deathwish11** [eartharoid/DiscordTickets#53]
So im trying to host my bot on pterodactyl panel and im struggling a bit on what goes where was just wondering if you could help quickly? Im quite new to hosting online

**Comment by Deathwish11** [comment]
Ive got the database connection details and theres loads of things which i dont know where to put

- Endpoint

- CONNECTION FROM

- USERNAME

- PASSWORD

- JBDC CONNECTION STRING

**Comment by eartharoid** [comment]
Unless you're using SQLite (default, no database server required), you need to set the `DB_` values in [.env](https://github.com/eartharoid/DiscordTickets/blob/master/user/.env#L5).

- `DB_HOST`: server IP - `host:port` (you can skip :port if it's the default)
- `DB_NAME`: name of the database (eg. "discord_bots")
- `DB_USER`: username
- `DB_PASS`: password

**Comment by Deathwish11** [comment]
Is there anything else i need to do other than that?

**Comment by eartharoid** [comment]
You need to edit `TOKEN` in that file, and you need to these in `config.js`:
- guild
- support_role
- tickets.category
- [storage.type (to your database server type)](https://github.com/eartharoid/DiscordTickets/wiki/Configuration#storagetype)

Make sure you invite your bot to your server.

**Comment by Deathwish11** [comment]
ok thankyou!

**Comment by Deathwish11** [comment]
[23:36:38 | LOGGER] Initialising logger (v2.0.5)
[23:36:38 | LOGGER] Preparing log file ("./logs/2020-10-16.log")
[23:36:39 | INFO] Connecting to MySQL database...
[23:36:39 | INFO] > Loaded debug event
[23:36:39 | INFO] > Loaded error event
[23:36:39 | INFO] > Loaded message event
[23:36:39 | INFO] > Loaded messageDelete event
[23:36:39 | INFO] > Loaded messageReactionAdd event
[23:36:39 | INFO] > Loaded messageUpdate event
[23:36:39 | INFO] > Loaded rateLimit event
[23:36:39 | INFO] > Loaded ready event
[23:36:39 | INFO] > Loaded warn event
[23:36:39 | INFO] > Loaded -add command
[23:36:39 | INFO] > Loaded -close command
[23:36:39 | INFO] > Loaded -delete command
[23:36:39 | INFO] > Loaded -help command
[23:36:39 | INFO] > Loaded -new command
[23:36:39 | INFO] > Loaded -panel command
[23:36:39 | INFO] > Loaded -remove command
[23:36:39 | INFO] > Loaded -rename command
[23:36:39 | INFO] > Loaded -stats command
[23:36:39 | INFO] > Loaded -tickets command
[23:36:39 | INFO] > Loaded -topic command
[23:36:39 | INFO] > Loaded -transcript command
[23:36:39 | INFO] Loaded 9 events and 12 commands
[23:36:39 | WARN] An error was not caught
[23:36:39 | WARN] Uncaught Error [TOKEN_INVALID]: An invalid token was provided.
[23:36:39 | ERROR] Error [TOKEN_INVALID]: An invalid token was provided.
    at Client.login (/home/container/node_modules/discord.js/src/client/Client.js:205:52)
    at Object.<anonymous> (/home/container/src/index.js:163:8)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
[23:36:39 | WARN] An error was not caught
[23:36:39 | WARN] Uncaught SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306
[23:36:39 | ERROR] SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306
    at ConnectionManager.connect (/home/container/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:116:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ConnectionManager._connect (/home/container/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:318:24)
    at async /home/container/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:250:32
[23:36:39 | WARN] An error was not caught
[23:36:39 | WARN] Uncaught SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306
[23:36:39 | ERROR] SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306
    at ConnectionManager.connect (/home/container/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:116:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ConnectionManager._connect (/home/container/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:318:24)
    at async /home/container/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:250:32
[23:36:40 | NOTICE] There is an update available for Discord Tickets (v2.0.1 -> v2.1.1)

resize: Time out occurred

**Comment by Deathwish11** [comment]
The bot token is right, i just made sure of that
