### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by gamernathanyt** [eartharoid/DiscordTickets#8]
everytime i do node . 
it says this 
[20:27:08 | ERROR] Uncaught error: 
TypeError: RichEmbed is not a constructor
    at Client.<anonymous> (C:\Users\nathan\Desktop\PlexTickets\index.js:86:19)
    at Object.onceWrapper (events.js:417:28)
    at Client.emit (events.js:311:20)
    at WebSocketManager.triggerClientReady (C:\Users\nathan\Desktop\PlexTickets\node_modules\discord.js\src\client\websocket\WebSocketManager.js:433:17)
    at WebSocketManager.checkShardsReady (C:\Users\nathan\Desktop\PlexTickets\node_modules\discord.js\src\client\websocket\WebSocketManager.js:417:10)
    at WebSocketShard.<anonymous> (C:\Users\nathan\Desktop\PlexTickets\node_modules\discord.js\src\client\websocket\WebSocketManager.js:199:14)
    at WebSocketShard.emit (events.js:311:20)
    at WebSocketShard.checkReady (C:\Users\nathan\Desktop\PlexTickets\node_modules\discord.js\src\client\websocket\WebSocketShard.js:466:12)
    at WebSocketShard.onPacket (C:\Users\nathan\Desktop\PlexTickets\node_modules\discord.js\src\client\websocket\WebSocketShard.js:438:16)
    at WebSocketShard.onMessage (C:\Users\nathan\Desktop\PlexTickets\node_modules\discord.js\src\client\websocket\WebSocketShard.js:293:10)

**Comment by eartharoid** [comment]
Have you edited `index.js` much?
https://github.com/eartharoid/DiscordTickets/blob/master/index.js#L86
there's nothing on line 86

**Comment by eartharoid** [comment]
If you still care: 
Use `npm i discord.js@11.6.4` to install the latest version of dicord.js 11.
v12 changes a lot and I haven't gotten around to updating the code yet.
