### ISSUE TITLE
Error when starting

### ISSUE THREAD

**Issue by mrcsdl** [eartharoid/DiscordTickets#98]
[14:16:57 | WARN] An error was not caught
[14:16:57 | WARN] Uncaught TypeError: Cannot read property 'member' of undefined
[14:16:57 | ERROR] TypeError: Cannot read property 'member' of undefined
    at Object.execute (/home/bot/DiscordTickets/src/events/ready.js:37:44)
    at Client.client.on (/home/bot/DiscordTickets/src/index.js:130:68)
    at Client.emit (events.js:198:13)
    at WebSocketManager.triggerClientReady (/home/bot/DiscordTickets/node_modules/discord.js/src/client/websocket/WebSocketManager.js:431:17)
    at WebSocketManager.checkShardsReady (/home/bot/DiscordTickets/node_modules/discord.js/src/client/websocket/WebSocketManager.js:415:10)
    at WebSocketShard.shard.on.unavailableGuilds (/home/bot/DiscordTickets/node_modules/discord.js/src/client/websocket/WebSocketManager.js:197:14)
    at WebSocketShard.emit (events.js:198:13)
    at WebSocketShard.checkReady (/home/bot/DiscordTickets/node_modules/discord.js/src/client/websocket/WebSocketShard.js:475:12)
    at WebSocketShard.onPacket (/home/bot/DiscordTickets/node_modules/discord.js/src/client/websocket/WebSocketShard.js:447:16)
    at WebSocketShard.onMessage (/home/bot/DiscordTickets/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    
    can someone help me with that? iam using ubuntu

**Comment by eartharoid** [comment]
You need to set the required values in your config: [configuration](https://github.com/eartharoid/DiscordTickets/wiki/Configuration#notice).

**Comment by mrcsdl** [comment]
i did that, all the required values are 
guild server id
staff_role admin id
tickets.category ticket channel id

right?

**Comment by eartharoid** [comment]
`tickets.category` is the ID of a channel category, not an actual text channel.

`TypeError: Cannot read property 'member' of undefined` means the bot couldn't find a server with the ID in the config. If you have entered the correct ID in the config, check you have invited the bot to your server.

**Comment by mrcsdl** [comment]
[14:50:55 | ERROR] TypeError: fields.flat is not a function
    at Function.normalizeFields (/home/bot/DiscordTickets/node_modules/discord.js/src/structures/MessageEmbed.js:450:8)
    at MessageEmbed.setup (/home/bot/DiscordTickets/node_modules/discord.js/src/structures/MessageEmbed.js:78:91)
    at new MessageEmbed (/home/bot/DiscordTickets/node_modules/discord.js/src/structures/MessageEmbed.js:18:10)
    at embedLikes.map.e (/home/bot/DiscordTickets/node_modules/discord.js/src/structures/APIMessage.js:166:40)
    at Array.map (<anonymous>)
    at APIMessage.resolveData (/home/bot/DiscordTickets/node_modules/discord.js/src/structures/APIMessage.js:166:31)
    at TextChannel.send (/home/bot/DiscordTickets/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:166:62)
    at guild.channels.create.then (/home/bot/DiscordTickets/src/commands/new.js:132:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    
    now this pops up when i try -help or -new

**Comment by eartharoid** [comment]
Update Node.JS to the latest version.

**Comment by mrcsdl** [comment]
solved thx
